ViridianCity_Fisherman_Text_ImFishingGuruDoYouLikeToFish::
    .string "Ich bin ein ANGLER!\p"
    .string "Ich liebe das Angeln über\n"
    .string "alles auf der Welt.\p"
    .string "Darum habe ich mich hier\n"
    .string "in VERTANIA niedergelassen.\p"
    .string "Sag mal, angelst du gern?$"

ViridianCity_Fisherman_Text_TakeThisAndFish::
    .string "Großartig! Das gefällt mir.\n"
    .string "Vielleicht verstehen wir uns.\p"
    .string "Hier, nimm das und\n"
    .string "geh an die Seen angeln!$"

ViridianCity_Fisherman_Text_ReceivedOldRodFromFishingGuru::
    .string "{PLAYER} erhielt die\n"
    .string "ALTE ANGEL vom Angler!$"

ViridianCity_Fisherman_Text_FishingIsAWayOfLife::
    .string "Angeln ist mehr als ein\n"
    .string "Hobby, es ist ein Lebensstil.\p"
    .string "Die Seen dieses Landes sind\n"
    .string "voller Geheimnisse.\p"
    .string "Geh raus und fang was\n"
    .string "Besonderes!$"

ViridianCity_Fisherman_Text_OhThatsSoDisappointing::
    .string "Oh...\n"
    .string "Das ist aber schade...$"

ViridianCity_Fisherman_Text_HowAreTheFishBiting::
    .string "Hallo, {PLAYER}!\p"
    .string "Beißen die Fische gut?$"

ViridianCity_Fisherman_Text_NoRoomForNiceGift::
    .string "Oh nein!\p"
    .string "Ich wollte dir etwas geben,\n"
    .string "aber dein BEUTEL ist voll!$"
