VermilionCity_Fisherman_Text_ImFishingGuruDoYouLikeToFish::
    .string "Ich bin ein ANGLER!\p"
    .string "Am liebsten angle ich\n"
    .string "hier am Fluss von ORANIA.\p"
    .string "Das ruhige Wasser und\n"
    .string "die Strömung sind perfekt.\p"
    .string "Sag, angelst du auch gern?$"

VermilionCity_Fisherman_Text_TakeThisAndFish::
    .string "Ha! Das höre ich gern.\n"
    .string "Du hast den richtigen Geist.\p"
    .string "Hier, nimm diese Angel\n"
    .string "und versuch dein Glück!$"

VermilionCity_Fisherman_Text_ReceivedGoodRodFromFishingGuru::
    .string "{PLAYER} erhielt die\n"
    .string "GUTE ANGEL vom Angler!$"

VermilionCity_Fisherman_Text_FishingIsAWayOfLife::
    .string "Flussangeln braucht Geduld\n"
    .string "und ein gutes Gespür.\p"
    .string "Mit der richtigen Angel\n"
    .string "wartet immer ein Fang.\p"
    .string "Viel Erfolg am Wasser!$"

VermilionCity_Fisherman_Text_OhThatsSoDisappointing::
    .string "Oh...\n"
    .string "Das ist wirklich schade...$"

VermilionCity_Fisherman_Text_HowAreTheFishBiting::
    .string "Hey, {PLAYER}!\p"
    .string "Wie läuft das Angeln?$"

VermilionCity_Fisherman_Text_NoRoomForNiceGift::
    .string "Oh nein!\p"
    .string "Dein BEUTEL ist voll.\n"
    .string "Komm später wieder!$"
