FuchsiaCity_House2_Text_CongratsYouveWon::
    .string "Ah! Hallo!\p"
    .string "Ich lebe hier in FUCHSANIA\n"
    .string "und angle meist draußen\n"
    .string "auf dem offenen Meer.\p"
    .string "Du kannst das sicher\n"
    .string "gut gebrauchen!$"

FuchsiaCity_House2_Text_ReceivedHM03FromAttendant::
    .string "{PLAYER} erhielt VM03\n"
    .string "vom Fischer!$"

FuchsiaCity_House2_Text_ExplainSurf::
    .string "VM03 ist SURFER.\p"
    .string "Damit können POKéMON\n"
    .string "dich über Wasser tragen.\p"
    .string "So erreichst du die besten\n"
    .string "Plätze zum Hochseeangeln!\p"
    .string "Pass gut darauf auf!$"

FuchsiaCity_House2_Text_DontHaveRoomForPrize::
    .string "Dein BEUTEL ist voll.\n"
    .string "Komm später wieder!$"
