ViridianCity_Text_CanCarryMonsAnywhere::
    .string "Those POKé BALLS at your waist!\n"
    .string "You have POKéMON, don't you?\p"
    .string "It's great that you can carry and\n"
    .string "use POKéMON anytime, anywhere.$"

ViridianCity_Text_GymClosedWonderWhoLeaderIs::
    .string "Wird dieses POKéMON Arena jemals geöffnet?\p"
    .string "Wer ist wohl der Leiter?\p"
    .string "Ich bin mir sicher, dass er sehr stark ist.$"

ViridianCity_Text_ViridiansGymLeaderReturned::
    .string "VERTANIA Arenaleiter ist zurück!$"

ViridianCity_Text_WantToKnowAboutCaterpillarMons::
    .string "Kennst du den unterschiedt,\n"
    .string "zwischen den Raupen POKéMON?$"

ViridianCity_Text_OhOkayThen::
    .string "Wie, nein!$"

ViridianCity_Text_ExplainCaterpieWeedle::
    .string "RAUPY hat kein Gift,\n"
    .string "aber darfür Hornliu.\p"
    .string "Achte auf dein POKéMON,\n"
    .string "dass es nicht von Hornliu gestochen wird.$"

ViridianCity_Text_GrandpaHasntHadCoffeeYet::
    .string "Oh, Grandpa!\n"
    .string "Don't be so mean!\p"
    .string "I'm so sorry.\n"
    .string "He hasn't had his coffee yet.$"

ViridianCity_Text_GoShoppingInPewterOccasionally::
    .string "Ich shopper lieber in MAMORIA CITY\n"
    .string "da gibst viel mehr Auswahl.\p"
    .string "Nur muss ich wieder diesen,\n"
    .string "durch den VERTANIA WALD gehen stöhn.$"

ViridianCity_Text_ThisIsPrivateProperty::
    .string "Was willst du den hier\n"
    .string "lass uns ihn Ruhe!\p"
    .string "Das ist Privat Gelände!$"

ViridianCity_Text_ShowYouHowToCatchMons::
    .string "Well, now, I've had my coffee, and\n"
    .string "that's what I need to get going!\p"
    .string "Hm?\n"
    .string "What is that red box you have?\p"
    .string "Ah, so you're working on your\n"
    .string "POKéDEX.\p"
    .string "Then let me give you a word of\n"
    .string "advice.\p"
    .string "Whenever you catch a POKéMON,\n"
    .string "the POKéDEX automatically updates\l"
    .string "its data.\p"
    .string "…You don't know how to catch\n"
    .string "a POKéMON?\p"
    .string "I suppose I had better show you\n"
    .string "then!$"

ViridianCity_Text_ThatWasEducationalTakeThis::
    .string "There! Now tell me, that was\n"
    .string "educational, was it not?\p"
    .string "And here, take this, too.$"

ViridianCity_Text_WatchThatToLearnBasics::
    .string "If there's something you don't\n"
    .string "understand, watch that.\p"
    .string "It will teach you about the basics\n"
    .string "of being a POKéMON TRAINER.$"

ViridianCity_Text_WeakenMonsFirstToCatch::
    .string "Well, now, I've had my coffee, and\n"
    .string "that's what I need to get going!\p"
    .string "But I made it too strong.\n"
    .string "It gave me a headache…\p"
    .string "Incidentally, are you filling your\n"
    .string "POKéDEX?\p"
    .string "At first, focus on weakening the\n"
    .string "POKéMON before trying to catch it.$"

ViridianCity_Text_HowsTeachyTVHelping::
    .string "Well, now, I've had my coffee, and\n"
    .string "that's what I need to get going!\p"
    .string "But I made it too strong.\n"
    .string "It gave me a headache…\p"
    .string "Incidentally, is my old TEACHY TV\n"
    .string "helping you?$"

ViridianCity_Text_MyGrandsonOnTheShow::
    .string "Wahaha!\n"
    .string "It's my grandson on the show!\p"
    .string "Since he's the one doing the\n"
    .string "teaching, you're bound to learn.$"

ViridianCity_Text_TooBusyForTeachyTV::
    .string "Hm… You're too busy to not even\n"
    .string "have the time for TEACHY TV…\p"
    .string "Time is money, and neither should\n"
    .string "be ill spent…$"

ViridianCity_Text_CitySign::
    .string "VERTANIA CITY \n"
    .string "Eine Stadt im schönen Grün$"

ViridianCity_Text_CatchMonsForEasierBattles::
    .string "TRAINER TIPPS\p"
    .string "Fange POKéMON, um das beste\n"
    .string "Team zu bilden.\p"
    .string "Je mehr du hast, um so einfacher\n"
    .string "wirst du dein Kampf gewinnen.$"

ViridianCity_Text_MovesLimitedByPP::
    .string "TRAINER TIPPS\p"
    .string "Dein ATTACKEN der POKéMON\n"
    .string "sind sehr limitiert, auf die AP.\p"
    .string "Um die AP wieder aufzufüllen, heilen\n"
    .string "dein POKéMON im POKéMON CENTER.$"

ViridianCity_Text_GymSign::
    .string "VERTANIA CITY POKéMON GYM$"

ViridianCity_Text_GymDoorsAreLocked::
    .string "VERTANIA GYM's Tür sind versperrt…?$"

ViridianCity_Text_CityTaubsi::
	.string "Kurukkoo!$"

